version: "3.3"

services:
  globus-connect:
    build:
      context: .
      dockerfile: Dockerfile.globus-connect
    container_name: globus_connect_container
    environment:
      - DataPath=${DataPath}
      - ConfigPath=${ConfigPath}
      - START_GLOBUS=true
    volumes:
      - ${ConfigPath}:/home/gridftp/globus_config
      - ${DataPath}:/home/gridftp/data
      - shared-data:/shared-data
    networks:
      - app-network
    ports:
      - "2811:2811"
      - "7512:7512"
      - "7513:7513"
    restart: unless-stopped

  python-fetch:
    build:
      context: .
      dockerfile: Dockerfile.datafed
    container_name: python_fetch_container
    environment:
      - ENDPOINT_URL=http://globus_connect_container:7512/endpoint
    volumes:
      - shared-data:/shared-data
    networks:
      - app-network
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge
