image:
  repository: jagar2/globus-connect-personal
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

dataPath: /data
configPath: /.config

currentUser: ferroelectric

# PVCs
persistence:
  config:
    enabled: true
    size: 100Mi
    storageClass: rook-cephfs
  data:
    enabled: true
    size: 1Gi
    storageClass: rook-cephfs