apiVersion: apps/v1
kind: Deployment
metadata:
  name: globus-connect-configure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globus-connect
  template:
    metadata:
      labels:
        app: globus-connect
    spec:
      containers:
      - name: globus-connect-container
        image: jagar2/globuspersonaldocker:latest
        imagePullPolicy: Always
        env:
        - name: DataPath
          value: "/home/gridftp/data" 
        - name: ConfigPath
          value: "/home/gridftp/globus_config" # Use ConfigMap or Secret for sensitive data
        - name: START_GLOBUS
          value: "false"
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /home/gridftp/globus_config
        - name: shared-data
          mountPath: /shared-data
        - name: globus-data
          mountPath: /home/gridftp/data
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: globus-config-pvc
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
      - name: globus-data
        persistentVolumeClaim:
          claimName: globus-data-pvc
