apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "globus-personal-docker.fullname" . }}-config
  labels:
    app: {{ include "globus-personal-docker.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "globus-personal-docker.fullname" . }}-data
  labels:
    app: {{ include "globus-personal-docker.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}